// AION_a21oi_nor2_1 -- Verilog model for gate-level simulation.
//
// GENERATED by aion_layout.exporters from AION_a21oi_nor2_1_minimized.spice -- do not edit by hand.
//
// The function below is solved from the transistor netlist the layout was
// drawn against (aion_layout.logic: a DC switch-level solve, one input
// vector at a time), not transcribed from a schematic.
//
// AION_a21oi_nor2_1_typ_1p20V_25C.lib: pin O0 function agrees
//
// The specify block carries one zero-delay path per timing arc, which is
// what an SDF IOPATH record annotates. iverilog keeps specify blocks only
// with -gspecify; Questa keeps them by default; Verilator ignores them and
// simulates this model at zero delay, which is all it ever does with a gate
// netlist. So this one file serves the timed and the untimed runs both.
//
// STA does not read this file, and the marker below is what tells OpenSTA's
// Verilog reader to skip it. No timing is lost by that: the cell's arcs come
// from its .lib, which LibreLane loads first (EXTRA_LIBS), so the instance
// links as a liberty leaf cell and is timed like any PDK cell. Without the
// marker OpenSTA aborts the whole run on the assign expression below --
// its reader takes structural netlists only, not operators or specify.
/// sta-blackbox

`timescale 1ns / 10ps
`celldefine
module AION_a21oi_nor2_1 (
`ifdef USE_POWER_PINS
    inout VDD,
    inout VSS,
`endif
    output O0,
    input I0,
    input I1,
    input I2,
    input I3
);

  // Function
  assign O0 = ~((I0 & I1) | (~I2 & ~I3));

  // Timing
  specify
    (I0 => O0) = (0.0, 0.0);
    (I1 => O0) = (0.0, 0.0);
    (I2 => O0) = (0.0, 0.0);
    (I3 => O0) = (0.0, 0.0);
  endspecify

endmodule
`endcelldefine
