#!/usr/bin/env python3
# ================================================================
#  SPDX-FileCopyrightText:    2026 Filippo Quadri
#  SPDX-License-Identifier:   Apache-2.0 WITH SHL-2.1
#  Description:               Regenerate the FuseSoC handle on the PDK
#                             extension cells' LEAF models
#
#  Two Verilog views of the same cell, and which one is right depends on
#  where in the flow you are.
#
#    <CELL>.v         the hand-written structural gold reference -- a PDK mux2
#                     and a PDK inverter. What `aion_char` proves the design
#                     against, and what the *post-synthesis* simulation reads,
#                     because there the netlist calls AION_mux2i_1 and the
#                     things it is made of are ordinary cells.
#
#    <CELL>.layout.v  the behavioural model `aion_layout export` solved from
#                     the transistor netlist, with a specify block. What the
#                     *post-PnR* simulation needs: LibreLane hardens the cell
#                     as a leaf and the SDF carries one CELL entry per
#                     instance, so a structural model would describe a
#                     hierarchy the netlist and the SDF do not have, and every
#                     IOPATH record for it would annotate nothing.
#
#  `implementation/pdk_extension/pdk_extension.core` is the hand-kept handle
#  on the first. This writes the handle on the second, and it is generated
#  rather than hand-kept for one reason: `<CELL>.layout.v` does not exist
#  until the cell has been drawn, and a FuseSoC fileset naming a file that is
#  not there fails every target that depends on it -- including the ones that
#  have nothing to do with these cells. The same reason flow step 6 generates
#  flow/aion_cells.core for the mined cells, and the same placeholder when
#  there is nothing to list.
#
#      make pdk_ext_lib            runs this
#      scripts/pdk_ext_core.py     just this
# ================================================================

from __future__ import annotations

import argparse
import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

DEFAULT_EXT_ROOT = PROJECT_ROOT / "implementation" / "pdk_extension"
DEFAULT_OUT = DEFAULT_EXT_ROOT / "pdk_extension_cells.core"

#: Listed when no cell has been drawn -- the same empty module file flow step
#: 6 falls back to. A fileset with no files at all would also load, and the
#: simulation would then die at elaboration with `Unknown module type` rather
#: than here, where the reason is knowable.
PLACEHOLDER = PROJECT_ROOT / "flow" / "no_aion_cells.v"

TEMPLATE = """CAPI=2:

# ================================================================
#  Project:     AION
#  Author:      Filippo Quadri <filippo.quadri@epfl.ch>
#  Description: Leaf models of the drawn PDK-extension cells
#
#  GENERATED BY scripts/pdk_ext_core.py -- edits here are overwritten by
#  `make pdk_ext_lib`.
# ================================================================

name: epfl:aion:pdk_extension_cells:1.0.0
description: |
  Verilog models of the hand-designed cells under
  implementation/pdk_extension/ that have been drawn and published.
  Currently: {summary}.

  Not the same views as epfl:aion:pdk_extension:1.0.0, which carries each
  cell's structural `<CELL>.v` gold reference for the post-synthesis
  simulation. After PnR the cell is a LEAF -- LibreLane hardens it as a macro
  and the SDF carries one CELL entry per instance -- so the post-PnR run needs
  `<CELL>.layout.v`, the behavioural model solved from the transistor netlist,
  with the specify block an IOPATH record annotates. Reading both would define
  every module twice.

filesets:
  models:
    files:
{listed}
    file_type: verilogSource

targets:
  default: &default
    filesets:
      - models
    toplevel: tt_um_aion
"""


def models(ext_root: Path) -> "list[tuple[str, Path]]":
    """Every `<CELL>/<CELL>.layout.v` on disk, as (cell, path)."""
    if not ext_root.is_dir():
        return []
    found = []
    for directory in sorted(p for p in ext_root.iterdir() if p.is_dir()):
        model = directory / f"{directory.name}.layout.v"
        if model.is_file():
            found.append((directory.name, model))
    return found


def render(found, out: Path) -> str:
    # FuseSoC resolves a fileset's files against the .core file's own
    # directory, so they are written relative to wherever --out lands.
    paths = [path for _, path in found] or [PLACEHOLDER]
    files = [os.path.relpath(path, out.parent) for path in paths]
    summary = (f"{len(found)} drawn cell(s): "
               + ", ".join(name for name, _ in found)) if found else \
        "no extension cell has been drawn yet -- this is the placeholder"
    return TEMPLATE.format(
        summary=summary,
        listed="\n".join(f"      - {f}" for f in files),
    )


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate the FuseSoC handle on the PDK-extension "
                    "cells' post-PnR leaf models.")
    parser.add_argument("--ext-root", type=Path, default=DEFAULT_EXT_ROOT,
                        help=f"default: "
                             f"{DEFAULT_EXT_ROOT.relative_to(PROJECT_ROOT)}")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT,
                        help=f"default: "
                             f"{DEFAULT_OUT.relative_to(PROJECT_ROOT)}")
    args = parser.parse_args(argv)

    found = models(args.ext_root)
    text = render(found, args.out)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    if args.out.exists() and args.out.read_text() == text:
        # Rewriting an identical file would bump its mtime, and `make pnr`
        # runs this every time.
        print(f"[pdk_ext_core] {args.out.relative_to(PROJECT_ROOT)} unchanged "
              f"({len(found)} model(s))")
        return 0
    args.out.write_text(text)
    print(f"[pdk_ext_core] wrote {args.out.relative_to(PROJECT_ROOT)} with "
          + (", ".join(name for name, _ in found) if found
             else "the placeholder — no drawn extension cell"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
